server.port: 7001
server.error.include-message: always

# recommend setting this to "none" for production environments
spring.jpa.hibernate.ddl-auto : update

spring.datasource:
  url: jdbc:mysql://localhost:3306/movie-review-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.forest: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.profiles: docker

spring.datasource:
  url: jdbc:mysql://mysql/movie-review-db

server.port: 8080